### PR TITLE
Add Carthage support

### PR DESCRIPTION
**Pull request by libec**
I'm so sorry guys :( Feels like I'm betraying @orta but someone had to do it :]

### CODE REVIEW

**Comment by orta** [comment]
eh, I'd be more interested in seeing SwiftPM support :P

**Comment by ashfurrow** [comment]
Looks fine to me – I understand other people want to use other dependency managers, that's fine. As long as I don't have to do the work :stuck_out_tongue: 

Related: @libec I've invited you to the RxSwiftCommunity organization, thanks a lot for your contribution! You can read more in our contributor guidelines: https://github.com/RxSwiftCommunity/contributors

**Comment by ashfurrow** [comment]
We should probably update the readme too with Carthage instructions, whoever you get a chance :bow:

**Comment by libec** [comment]
OKay, thanks :) I'll read the guidelines and update the readme accordingly :+1:

**Pull request merged**
