### PR TITLE
Xcode8 GM and swift3

### PR DESCRIPTION
**Pull request by tcurdt**
currently only the RxSwift develop branch builds OK hence the reference to the branch,
adjusted the version according to semver rules,
updated the travis image (let's hope that builds)

includes https://github.com/RxSwiftCommunity/NSObject-Rx/pull/24

### CODE REVIEW

**Comment by ashfurrow** [comment]
Weird! Okay, I'm going to merge #24 so @zhouhao27 gets invited to the org, then this, then we can deal with CI separately.

**Comment by ashfurrow** [comment]
Oh no! Merge conflict :( Want to pull/push to your branch and then we can merge?

**Comment by ashfurrow** [comment]
Thanks a lot for contributing! I've invited you to join the RxSwiftCommunity GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/RxSwiftCommunity/contributors) and feel free to reach out with any questions.

**Comment by tcurdt** [comment]
Thanks, Ash!

**Pull request merged**
