### PR TITLE
Make rx.disposeBag public

### PR DESCRIPTION
**Pull request by RafaelPlantard**
To allow us use it into a UIViewController for example.

### CODE REVIEW

**Comment by freak4pc** [comment]
Looks good to me. Actually planned on doing this earlier on. 
Any reason CI was updated to use Xcode 8.3 ?

**Comment by RafaelPlantard** [comment]
Nope, I guess! I just based at https://github.com/RxSwiftCommunity/RxNimble/blob/master/.travis.yml

**Review by ashfurrow — APPROVED** [review]

**Comment by ashfurrow** [comment]
Thanks a lot for contributing! I've invited you to join the RxSwiftCommunity GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/RxSwiftCommunity/contributors) and feel free to reach out with any questions.

**Comment by RafaelPlantard** [comment]
Thanks @ashfurrow @freak4pc

**Pull request merged**
