### PR TITLE
Added rx_observableForSelector to NSObject

### PR DESCRIPTION
**Pull request by sergdort**
Hi, guys I remember we had some [discussion](https://github.com/ReactiveX/RxSwift/issues/181) regarding observing method calls on main Rx repo

Almost all implementation has been taken from [RAC](https://github.com/ReactiveCocoa/ReactiveCocoa/blob/master/ReactiveCocoa/Objective-C/NSObject%2BRACSelectorSignal.m)

I'm still not sure about naming conventions and whether I completely covered implementation with test, and whether you want this feature in this repo :)

But I open for discussion :)

### CODE REVIEW

**Comment by ashfurrow** [comment]
Hey there! Just so you know this is on my radar, but I haven't had time to review yet. If anyone from @RxSwiftCommunity/contributors has time to look this over and post feedback, that would be awesome :bow:

**Comment by kzaher** [comment]
Hey guys @ashfurrow , @sergdort ,

I was first against including this in RxCocoa repository, but since it seemed people really wanted this feature I've decided to include this functionality in RxCocoa repository some time ago in RxCocoa 2.0.0-rc.0. It's called `rx_sentMessage` in the main repo.

It seems to me that this is similar functionality, so I'm little confused :)

**Comment by ashfurrow** [comment]
@kzaher hmm right, that sounds familiar. @sergdort does [this](https://github.com/ReactiveX/RxSwift/blob/6df77da4745338fa13986d044f6b764af4c3d99f/RxCocoa/Common/Observables/NSObject%2BRx.swift#L119-L128) solve your needs?

**Comment by sergdort** [comment]
Ha, @kzaher  right, did see it there :)

My bad:)

**Comment by onmyway133** [comment]
@sergdort Hi, I think @kzaher makes this for the community only, although it is not recommended, and he does not advise it. I think we should do it explicitly, by using `Subject` for example

**Pull request closed without merging**
