### PR TITLE
Feature: Add HasDisposeBag.swift to .xcodeproj

### PR DESCRIPTION
**Pull request by Gurpartap**
Related to #49 and #55.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Thanks @Gurpartap – sorry for all the hassle with Carthage support. I really appreciate you taking the time to help.

**Review by ashfurrow — APPROVED** [review]

**Comment by Gurpartap** [comment]
18c6c627-55b8-49fa-b65c-cd3df591e476

**Comment by ashfurrow** [comment]
Awesome – I've released this change as version 4.2.0. If there are any more issues, just let us know 👍

**Comment by freak4pc** [comment]
@ashfurrow Seems like this broke CI ?

**Comment by ashfurrow** [comment]
Strange – I've pushed a commit to fix this by running `pod install`: https://github.com/RxSwiftCommunity/NSObject-Rx/commit/05893151af80d29b29cfb7d9ef4f5854daeaf866

**Comment by freak4pc** [comment]
¯\_(ツ)_/¯

**Pull request merged**
