### PR TITLE
Moves to Circle CI and checks in Pods folder

### LINKED ISSUE #52: Switch CI to Circle
Travis builds are taking hours just to queue, we need to switch to Circle. I'll try to get to this unless someone wants to tackle it first 👍

### PR DESCRIPTION
**Pull request by ashfurrow**
Fixes #52.

### CODE REVIEW

**Comment by ashfurrow** [comment]
Okay, this is ready for review 👍

**Comment by freak4pc** [comment]
Ouchie
55ab96d5-3001-413e-a9e8-16b350e4cd18

**Review by freak4pc — APPROVED** [review]
LGTM :shipit:

**Comment by ashfurrow** [comment]
Cool cool. Yeah it'll be nice once your PR to ignore the `CocoaPods` folder in PRs gets merged. But I got our CI build times to less than two minutes, which will help as we continue to iterate and improve this library. I'm hoping that this PR, and https://github.com/RxSwiftCommunity/Action/pull/124 , will become models that other @RxSwiftCommunity/contributors can use to move projects to Circle (no pressure!).

**Pull request merged**
