### PR TITLE
hotfix: RxSwift 4.0 and Carthage ketchup

### PR DESCRIPTION
**Pull request by Gurpartap**
catch up*

I've removed the missing HasDisposeBag.swift reference from the Xcode project so that the project compiles. Perhaps RxSwiftCommunity/NSObject-Rx/pull/49 can suitably add it back.

### CODE REVIEW

**Comment by Gurpartap** [comment]
```sh
$ cd ~/path/to/SomeProject/
$ cat Cartfile
```
```
github "Gurpartap/NSObject-Rx" "master"
```
```sh
$ carthage update --platform iOS --no-use-binaries
*** Fetching NSObject-Rx
*** Fetching RxSwift
*** Checking out RxSwift at "4.0.0"
*** Checking out NSObject-Rx at "79bb89e870ad7d10242069965c9d8f08e97c9378"
*** ...
*** Building scheme "RxSwift-iOS" in Rx.xcworkspace
*** Building scheme "NSObject_Rx" in NSObject-Rx.xcodeproj
```

**Review by ashfurrow — APPROVED** [review]
Awesome, looks good. CI failure is unrelated, I'm fine with merging this – let me know what I can to do help.

**Comment by Gurpartap** [comment]
The above output demonstrates the resolved RxSwift version after the PR patch, which is 4.0 instead of the incompatible 3.6.x before.

LGTM. Merge and release?

**Comment by ashfurrow** [comment]
Thanks a lot for contributing! I've invited you to join the RxSwiftCommunity GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/RxSwiftCommunity/contributors) and feel free to reach out with any questions.

**Pull request merged**
