### PR TITLE
remove RxSwift version

### PR DESCRIPTION
**Pull request by xixi197**

### CODE REVIEW

**Comment by ashfurrow** [comment]
Fab, thanks!

**Comment by ashfurrow** [comment]
Hey there! Thanks a lot for contributing! I've invited you to join the RxSwiftCommunity GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/RxSwiftCommunity/contributors) and feel free to reach out with any questions.

**Comment by ashfurrow** [comment]
Just FYI, I re-added the `~> 2.0` specifier in the podspec: https://github.com/RxSwiftCommunity/NSObject-Rx/commit/0455d554efa6e55a3171c268e98c54751d1d5421 Unless you're looking for 1.0 compatibility, too? I suppose that would work... let me know!

**Comment by xixi197** [comment]
I just want to use newest RxSwift version(RxSwift 2.1), Thanks！I also want to join the RxSwiftCommunity GitHub organization

**Comment by ashfurrow** [comment]
Super!

**Pull request merged**
