### PR TITLE
Updated Swift to 5.0 from 3.0.

### PR DESCRIPTION
**Pull request by h1d3mun3**
Updated Swift Language Version to 4.2 from 3.0.

### CODE REVIEW

**Comment by pchelnikov** [comment]
What about Swift 5.0?

**Comment by h1d3mun3** [comment]
@pchelnikov Thanks for comment!

I update Swift to 4.2 from 3.0.
But now, I think had better updated to 4.0.

Because, current `RxSwift` is supported `Swift 4.0`.

What do you think about this?

**Comment by fassko** [comment]
There is .swift-version file which has 4.2 but with new Cocoapods this is being deprecated and can be removed maybe with this PR?

For backward compatibility I would make tag for 4.2 and bump version to 5.0.

**Comment by h1d3mun3** [comment]
@fassko Thanks for comments!

Unfortunately I'm not sure about a Cocoapods, so i would like to fix that problem with different PR.

> For backward compatibility I would make tag for 4.2 and bump version to 5.0.

I am a bit confused. (I'm so so sorry.)

Does it mean that update swift version to 5.0 with this PR? 🤔

**Comment by fassko** [comment]
Sorry @h1d3mun3-74k4h45h1 

I will merge this in coming future (right now I'm a bit busy) and do the rest then. I just don't want to merge this now because things I mentioned I need to do after that right away.

If you need this version, just point to your branch in Podfile and use it.

**Comment by h1d3mun3** [comment]
@fassko Oh I get it! Understood!

**Comment by RafaelPlantard** [comment]
Let's upgrade to 5.0? Now RxSwift also supports Swift 5.0

**Comment by h1d3mun3** [comment]
@RafaelPlantard Thank you for information! Make it Swift5!

**Comment by tomokisun** [comment]
Hello
Do not merge this PR?

**Pull request merged**
