### PR TITLE
Add SPM support

### PR DESCRIPTION
**Pull request by pomozoff**
#trivial

### CODE REVIEW

**Comment by ashfurrow** [comment]
Thanks for opening the PR!

It looks like CocoaPods is adding `Package.swift` to the CocoaPod podspec 😅 

https://github.com/RxSwiftCommunity/NSObject-Rx/blob/11e5a2b812e52d3d70ec127b5581873015080520/NSObject%2BRx.podspec#L20

I think we can change this line to `%w(NSObject+Rx.swift HasDisposeBag.swift)` to fix CI. That and a changelog entry, and we should be good to merge!

**Comment by pomozoff** [comment]
@ashfurrow, thanks for helping! Should I replace `s.source_files  = "*.swift"` with `s.source_files  = "%w(NSObject+Rx.swift HasDisposeBag.swift)"`?

**Comment by ashfurrow** [comment]
Nearly! The `"quotes"` shouldn't be there. The way `%w()` works in Ruby is that it looks for whitespace in the parens, and separates out the text into an array divided by that whitespace. The following two lines are functionally identical:

```rb
s.source_files = ["NSObject+Rx.swift", "HasDisposeBag.swift"]
s.source_files = %w(NSObject+Rx.swift HasDisposeBag.swift)
``` 

One is just easier to copy/paste filenames into, so you see `%w()` (or `%w[]`) used a lot in Ruby :👍 Let me know what I can clarify.

**Comment by pomozoff** [comment]
Thank you a lot! Everything is clear now )

**Review by ashfurrow — APPROVED** [review]
Let's merge when CI is green. Then we can tag a release 👍

**Comment by ashfurrow** [comment]
Okay, tagged a release of 5.0.3 on git. Let me know if I can help further, and thanks again!

**Pull request merged**
