### PR TITLE
Fix CI

### LINKED ISSUE #23: Fix CI
CI is broken: https://travis-ci.org/RxSwiftCommunity/NSObject-Rx/builds/155059995

Haven't had a chance to look into it, help would be appreciated :bow:

### PR DESCRIPTION
**Pull request by toshi0383**
Fixes #23

### CODE REVIEW

**Comment by toshi0383** [comment]
Oh I have no idea what's going on here. It doesn't repro on my machine but on travis.
```
Installing Pods with 'pod install'
7.22s$ pod install
Analyzing dependencies
Fetching podspec for `NSObject+Rx` from `../`
[!] Unable to satisfy the following requirements:
- `Nimble (= 6.1.0)` required by `Podfile`
- `Nimble (= 6.1.0)` required by `Podfile.lock`
None of your spec sources contain a spec satisfying the dependency: `Nimble (= 6.1.0)`.
You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.
Note: as of CocoaPods 1.0, `pod repo update` does not happen on `pod install` by default.
```

**Comment by reloni** [comment]
Hello.
Logs says: `Note: as of CocoaPods 1.0, pod repo update does not happen on pod install by default.`
So, maybe adding this into Travis file will help:
```
before_script:
- pod repo update
```

**Comment by toshi0383** [comment]
Thanks @reloni ! It worked.

**Comment by toshi0383** [comment]
But you know what.. how about us not depending CocoaPods dirty hack on CI everytime it breaks?

I mean, we can use Carthage and simply commit `Carthage/Build/iOS/`. CI don't need to think about compile or caching framework before actual test step runs. This way CI is always simple, faster and stable. I pushed 1c67f8f to demonstrate. You can see `.travis.yml` became a little bit smaller.

This is just an opinion and it's perfectly okay to keep using CocoaPods on CI too.👌 In that case, I can reset the last commit and I think this PR is ready to go.

**Comment by ashfurrow** [comment]
I really like having CocoaPods in CI, to make sure we don't break things. @toshi0383 this looks great, thanks so much for the work! Is it ready to be merged form your perspective?

**Comment by toshi0383** [comment]
> I really like having CocoaPods in CI, to make sure we don't break things.

Understood. I just deleted the last commit.

>  Is it ready to be merged form your perspective?

I'd say yes!👍

**Comment by ashfurrow** [comment]
Thanks a lot for contributing! I've invited you to join the RxSwiftCommunity GitHub organization – no pressure to accept! If you'd like more information on what that means, check out our [contributor guidelines](https://github.com/RxSwiftCommunity/contributors) and feel free to reach out with any questions.

**Pull request merged**
